import type { Metadata } from "next"
import "./globals.css"
import Provider from "@/components/providers/Provider"
import { initLifiConfig } from "@/lib/lifiConfig"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  await initLifiConfig()

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
